defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory:  /home/circleci/app

version: 2

jobs:
  build-test-push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: make build
      - run: make test
      - store_test_results:
          path: ~/app/tests/output
      - store_artifacts:
          path: ~/app/tests/output
      - run: gcloud auth configure-docker
      - run: make push
      - run:
          name: Notify failure
          when: on_fail
          command: notify-job-failure.sh

workflows:
  version: 2
  branch:
    jobs:
      - build-test-push:
          context: org-global
          filters:
            branches:
              ignore: master
            tags:
              only: /.*/
      # - test:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /.*/
      # - push:
      #     context: org-global
      #     filters:
      #       tags:
      #         only: /.*/
  # tag:
  #   jobs:
  #     - build-test-push
